name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || echo "CMake already installed";
          fi
        shell: bash

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -B build/${{ matrix.os }} -S .
        shell: bash

      - name: Build Shared Library
        run: cmake --build build/${{ matrix.os }} --target CryptoMaster_shared
        shell: bash

      - name: Build Static Library
        run: cmake --build build/${{ matrix.os }} --target CryptoMaster_static
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CryptoMaster-libraries-${{ matrix.os }}
          path: |
            build/${{ matrix.os }}/**/*.a
            build/${{ matrix.os }}/**/*.lib
            build/${{ matrix.os }}/**/*.so
            build/${{ matrix.os }}/**/*.dylib
            build/${{ matrix.os }}/**/*.dll