name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew install cmake || echo "CMake already installed";
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || echo "CMake already installed";
          fi
        shell: bash

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -B build -S .
        shell: bash

      - name: Build Project
        run: cmake --build build
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/
