name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shared_libs: [ON, OFF]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || echo "CMake already installed";
          fi
        shell: bash

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }} \
                -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=build/${{ matrix.os }} \
                -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/${{ matrix.os }} \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=build/${{ matrix.os }} \
                -B build/${{ matrix.os }} -S .
        shell: bash

      - name: Build Project
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake --build build/${{ matrix.os }} --config Release
          else
            cmake --build build/${{ matrix.os }}
          fi
        shell: bash

      - name: Package Artifacts
        run: |
          mkdir -p release
          zip -r release/CryptoMaster-${{ matrix.os }}-${{ matrix.shared_libs == 'ON' && 'dynamic' || 'static' }}.zip build/${{ matrix.os }}
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: CryptoMaster-${{ matrix.os }}-${{ matrix.shared_libs == 'ON' && 'dynamic' || 'static' }}
          path: release/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_id }}
          release_name: "Build CryptoMaster (Run ${{ github.run_id }})"
          draft: false
          prerelease: false
          files: ./artifacts/*.zip
