name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Release, Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install conan

      - name: Install CMake
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake;
          else
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System';
          fi

      - name: Install Dependencies
        run: |
          conan install . --output-folder=build --build=missing

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -B build -S .

      - name: Build Project
        run: cmake --build build

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure
