name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        shared_libs: [ON, OFF]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || echo "CMake already installed";
          fi
        shell: bash

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED_LIBS=${{ matrix.shared_libs }} \
                -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release_${{ matrix.shared_libs }} \
                -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release_${{ matrix.shared_libs }} \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release_${{ matrix.shared_libs }} \
                -B build/${{ matrix.os }}/Release_${{ matrix.shared_libs }} -S .
        shell: bash

      - name: Build Project
        run: cmake --build build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CryptoMaster-libraries-${{ matrix.os }}-${{ matrix.shared_libs }}
          path: |
            build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}/**/*.a
            build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}/**/*.lib
            build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}/**/*.so
            build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}/**/*.dylib
            build/${{ matrix.os }}/Release_${{ matrix.shared_libs }}/**/*.dll
