name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew install cmake || echo "CMake already installed";
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' || echo "CMake already installed";
          fi
        shell: bash

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DBUILD_SHARED_LIBS=ON \
                -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release \
                -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release \
                -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=build/${{ matrix.os }}/Release \
                -B build/${{ matrix.os }}/Release -S .
        shell: bash

      - name: Build Project
        run: cmake --build build/${{ matrix.os }}/Release
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: CryptoMaster-libraries-${{ matrix.os }}
          path: |
            build/${{ matrix.os }}/**/*.a
            build/${{ matrix.os }}/**/*.lib
            build/${{ matrix.os }}/**/*.so
            build/${{ matrix.os }}/**/*.dylib
            build/${{ matrix.os }}/**/*.dll
