name: Build CryptoMaster

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-type: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CMake
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y cmake;
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install cmake;
          else
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System';
          fi

      - name: Configure with CMake
        run: |
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} \
                -B build -S .

      - name: Build Project
        run: cmake --build build
